using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication1.Models
{

    // TODO: Option Strict Option ... Warning!!! not translated
    // TODO: Option Explicit On ... Warning!!! not translated

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 
    // ''<remarks/>
    //<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42");
    //,System.SerializableAttribute();
    //,System.Diagnostics.DebuggerStepThroughAttribute();
    //,System.ComponentModel.DesignerCategoryAttribute("code");
    //,(System.Xml.Serialization.XmlRootAttribute("", true) > Partial);
    public class eInvoice
    {
        [Key]
        public int eInvoiceId { get; set; }

        private string currencyCodeField;

        private string purchOrderNoField;

        private int payTypeField;

        private double amountField;

        private string invoiceDateField;

        private bool invoiceDateFieldSpecified;

        private string dueDateField;

        private bool dueDateFieldSpecified;

        private double vatAmountField;

        private string authorizorField;

        private string ourCustomerNoField;

        private string invoiceTypeField;

        private string supplierField;

        private string supplierNoField;

        private string invoiceNoField;

        private InvoiceAccounts[] accRowsField;

        private InvoiceRows[] itemRowField;

        private string ocrField;

        private double freightField;

        private bool freightFieldSpecified;

        private string vatCodeField;

        private string pgField;

        private string bgField;

        private string orgNoField;

        private string ourReferenceField;

        private string yourReferenceField;

        private string invoiceRecipientField;

        private string addressField;

        private string postCodeField;

        private string cityField;

        private string messageField;

        private double vatField;

        private double invoiceFeeField;

        private AuxParam auxPField;

        private string projectField;

        private string pdfPath;

        private bool readable;

        public IList<Images> ListImages;






        public eInvoice()
        {
            //base.New;
            // TODO: Labeled Arguments not supported. Argument: 1 := 'Namespace'
            // TODO: Labeled Arguments not supported. Argument: 2 := 'IsNullable'
            this.currencyCodeField = "SEK";
            this.purchOrderNoField = "";
            this.payTypeField = 0;
            this.authorizorField = "";
            this.ourCustomerNoField = "";
            this.invoiceTypeField = "D";
            this.supplierField = "";
            this.supplierNoField = "";
            this.ocrField = "";
            this.vatCodeField = "";
            this.pgField = "";
            this.bgField = "";
            this.orgNoField = "";
            this.ourReferenceField = "";
            this.yourReferenceField = "";
            this.invoiceRecipientField = "";
            this.addressField = "";
            this.postCodeField = "";
            this.cityField = "";
            this.messageField = "";
            this.vatField = 0;
            this.invoiceFeeField = 0;
            this.projectField = "";
            this.pdfPath = "";
            this.ListImages = new List<Images>();



        }

        // ''<remarks/>
        [System.ComponentModel.DefaultValueAttribute("SEK")]
        public string CurrencyCode
        {
            get
            {
                return this.currencyCodeField;
            }
            set
            {
                this.currencyCodeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string PurchOrderNo
        {
            get
            {
                return this.purchOrderNoField;
            }
            set
            {
                this.purchOrderNoField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0)]
        public int PayType
        {
            get
            {
                return this.payTypeField;
            }
            set
            {
                this.payTypeField = value;
            }
        }

        public double Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        public string InvoiceD
        {
            get
            {
                return this.invoiceDateField;
            }
            set
            {
                this.invoiceDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoiceDateSpecified
        {
            get
            {
                return this.invoiceDateFieldSpecified;
            }
            set
            {
                this.invoiceDateFieldSpecified = value;
            }
        }

        public string DueD
        {
            get
            {
                return this.dueDateField;
            }
            set
            {
                this.dueDateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DueDateSpecified
        {
            get
            {
                return this.dueDateFieldSpecified;
            }
            set
            {
                this.dueDateFieldSpecified = value;
            }
        }

        public double VatAmount
        {
            get
            {
                return this.vatAmountField;
            }
            set
            {
                this.vatAmountField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string Authorizor
        {
            get
            {
                return this.authorizorField;
            }
            set
            {
                this.authorizorField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string OurCustomerNo
        {
            get
            {
                return this.ourCustomerNoField;
            }
            set
            {
                this.ourCustomerNoField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("D")]
        public string InvoiceType
        {
            get
            {
                return this.invoiceTypeField;
            }
            set
            {
                this.invoiceTypeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string Supplier
        {
            get
            {
                return this.supplierField;
            }
            set
            {
                this.supplierField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string SupplierNo
        {
            get
            {
                return this.supplierNoField;
            }
            set
            {
                this.supplierNoField = value;
            }
        }

        public string InvoiceNo
        {
            get
            {
                return this.invoiceNoField;
            }
            set
            {
                this.invoiceNoField = value;
            }
        }

        public InvoiceAccounts[] AccRows
        {
            get
            {
                return this.accRowsField;
            }
            set
            {
                this.accRowsField = value;
            }
        }

        public InvoiceRows[] ItemRow
        {
            get
            {
                return this.itemRowField;
            }
            set
            {
                this.itemRowField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string Ocr
        {
            get
            {
                return this.ocrField;
            }
            set
            {
                this.ocrField = value;
            }
        }

        public double Freight
        {
            get
            {
                return this.freightField;
            }
            set
            {
                this.freightField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FreightSpecified
        {
            get
            {
                return this.freightFieldSpecified;
            }
            set
            {
                this.freightFieldSpecified = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string VatCode
        {
            get
            {
                return this.vatCodeField;
            }
            set
            {
                this.vatCodeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string Pg
        {
            get
            {
                return this.pgField;
            }
            set
            {
                this.pgField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string Bg
        {
            get
            {
                return this.bgField;
            }
            set
            {
                this.bgField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string OrgNo
        {
            get
            {
                return this.orgNoField;
            }
            set
            {
                this.orgNoField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string OurReference
        {
            get
            {
                return this.ourReferenceField;
            }
            set
            {
                this.ourReferenceField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string YourReference
        {
            get
            {
                return this.yourReferenceField;
            }
            set
            {
                this.yourReferenceField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string InvoiceRecipient
        {
            get
            {
                return this.invoiceRecipientField;
            }
            set
            {
                this.invoiceRecipientField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0)]
        public double Vat
        {
            get
            {
                return this.vatField;
            }
            set
            {
                this.vatField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(0)]
        public double InvoiceFee
        {
            get
            {
                return this.invoiceFeeField;
            }
            set
            {
                this.invoiceFeeField = value;
            }
        }

        public AuxParam AuxP
        {
            get
            {
                return this.auxPField;
            }
            set
            {
                this.auxPField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string Project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute("")]
        public string pdfPaths
        {
            get
            {
                return this.pdfPath;
            }
            set
            {
                this.pdfPath = value;
            }
        }
        public IList<Images> images1
        {
            get
            {
                return this.ListImages;
            }
            set
            {
                this.ListImages = value;
            }
        }
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Redable
        {
            get
            {
                return this.readable;
            }
            set
            {
                this.readable = value;
            }
        } 
    }
    public class Images
    {
        [Key]
        public int ImagesId { get; set; }

        public int eInvoiceId { get; set; }

        public string ImageName { get; set; }

        public string imageMimeType { get; set; }

        public byte[] ImageData { get; set; }
    }
    // ''<remarks/>
    //<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42");
    //,System.SerializableAttribute();
    //,System.Diagnostics.DebuggerStepThroughAttribute();
    //,System.ComponentModel.DesignerCategoryAttribute("code");
    //,(System.Xml.Serialization.XmlRootAttribute("", true) > Partial);
    public class InvoiceAccounts
        {
        [Key]
        public int InvoiceAccountsId { get; set; }

            private string accountField;

            private string profit_centreField;

            private string projectField;

            private string accAuthorizorField;

            private double debetAmountField;

            private double creditAmountField;

            private DateTime reg_dateField;

            public InvoiceAccounts()
            {
                //base.New;
                // TODO: Labeled Arguments not supported. Argument: 1 := 'Namespace'
                // TODO: Labeled Arguments not supported. Argument: 2 := 'IsNullable'
                this.accountField = "";
                this.profit_centreField = "";
                this.projectField = "";
                this.accAuthorizorField = "";
                this.debetAmountField = 0;
                this.creditAmountField = 0;
            }

            // ''<remarks/>
            public string Account
            {
                get
                {
                    return this.accountField;
                }
                set
                {
                    this.accountField = value;
                }
            }

            [System.ComponentModel.DefaultValueAttribute("")]
            public string Profit_centre
            {
                get
                {
                    return this.profit_centreField;
                }
                set
                {
                    this.profit_centreField = value;
                }
            }

            [System.ComponentModel.DefaultValueAttribute("")]
            public string Project
            {
                get
                {
                    return this.projectField;
                }
                set
                {
                    this.projectField = value;
                }
            }

            [System.ComponentModel.DefaultValueAttribute("")]
            public string AccAuthorizor
            {
                get
                {
                    return this.accAuthorizorField;
                }
                set
                {
                    this.accAuthorizorField = value;
                }
            }

            [System.ComponentModel.DefaultValueAttribute(0)]
            public double DebetAmount
            {
                get
                {
                    return this.debetAmountField;
                }
                set
                {
                    this.debetAmountField = value;
                }
            }

            [System.ComponentModel.DefaultValueAttribute(0)]
            public double CreditAmount
            {
                get
                {
                    return this.creditAmountField;
                }
                set
                {
                    this.creditAmountField = value;
                }
            }

            public DateTime Reg_date
            {
                get
                {
                    return this.reg_dateField;
                }
                set
                {
                    this.reg_dateField = value;
                }
            }
        }
        // ''<remarks/>
        //<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42");
        //,System.SerializableAttribute();
        //,System.Diagnostics.DebuggerStepThroughAttribute();
        //,(System.ComponentModel.DesignerCategoryAttribute("code") > Partial);
        public class AuxParam
        {
            [Key]
        public int AuxParmID { get; set; }

            private string companyField;

            private string vernoField;

            public AuxParam()
            {
            //base.New;
                
                this.companyField = "";
                this.vernoField = "";
            }

            // ''<remarks/>
            [System.ComponentModel.DefaultValueAttribute("")]
            public string Company
            {
                get
                {
                    return this.companyField;
                }
                set
                {
                    this.companyField = value;
                }
            }

            [System.ComponentModel.DefaultValueAttribute("")]
            public string Verno
            {
                get
                {
                    return this.vernoField;
                }
                set
                {
                    this.vernoField = value;
                }
            }
        }
        // ''<remarks/>
        //<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42");
        //,System.SerializableAttribute();
        //,System.Diagnostics.DebuggerStepThroughAttribute();
        //,System.ComponentModel.DesignerCategoryAttribute("code");
        //,(System.Xml.Serialization.XmlRootAttribute("", true) > Partial);
        public class InvoiceRows
        {
            [Key]
            public int InvoiceRowId { get; set; }

            private string itemRowField;

            public InvoiceRows()
            {
                //base.New;
                // TODO: Labeled Arguments not supported. Argument: 1 := 'Namespace'
                // TODO: Labeled Arguments not supported. Argument: 2 := 'IsNullable'
                this.itemRowField = "";
            }

            // ''<remarks/>
            [System.ComponentModel.DefaultValueAttribute("")]
            public string ItemRow
            {
                get
                {
                    return this.itemRowField;
                }
                set
                {
                    this.itemRowField = value;
                }
            }
        }

    }


